server:
  port: 9001

spring:
  application:
    name: MOVIE-CATALOG-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/regisration_service
    username: postgres
    password: atumar4031
  jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  jwt-secret: JWTSecret
  jwt-expiration-time: 164800000



resilience4j:
  circuitbreaker:
    instances:
      movieInfoService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        maxWaitDurationInHalfOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED